---
name: Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.129.0'
      - name: Build
        run: |
          make build
      - name: Deploy
        env:
          BRANCH: ${{ github.REF_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          make deploy
